vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        media_file:
            uri_prefix: ''
            upload_destination: '%app.upload.media_directory%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
