<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Les étiquettes deviennent une vraie entité, gérée depuis le back-office,
 * plutôt qu'une liste de mots recopiée dans chaque notification.
 *
 * Les étiquettes déjà saisies sont reprises : chaque nom rencontré donne une
 * ligne dans « tag », et les rattachements sont recréés. La casse de la
 * première occurrence l'emporte, les variantes se rejoignent.
 */
final class Version20260920140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Transforme les étiquettes en entité avec sa table de liaison';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(32) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_name ON tag (LOWER(name))');

        $this->addSql('CREATE TABLE media_tag (media_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(media_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_48D8C57EEA9FDD75 ON media_tag (media_id)');
        $this->addSql('CREATE INDEX IDX_48D8C57EBAD26311 ON media_tag (tag_id)');
        $this->addSql('ALTER TABLE media_tag ADD CONSTRAINT fk_media_tag_media FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE media_tag ADD CONSTRAINT fk_media_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');

        // Un nom par étiquette rencontrée, la première casse vue l'emporte.
        $this->addSql(<<<'SQL'
            INSERT INTO tag (name)
            SELECT DISTINCT ON (LOWER(nom)) nom
            FROM (
                SELECT LEFT(TRIM(valeur), 32) AS nom
                FROM media, LATERAL jsonb_array_elements_text(tags::jsonb) AS valeur
                WHERE TRIM(valeur) <> ''
            ) AS noms
            ORDER BY LOWER(nom), nom
            SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO media_tag (media_id, tag_id)
            SELECT DISTINCT m.id, t.id
            FROM media m, LATERAL jsonb_array_elements_text(m.tags::jsonb) AS valeur
            JOIN tag t ON LOWER(t.name) = LOWER(LEFT(TRIM(valeur), 32))
            WHERE TRIM(valeur) <> ''
            SQL);

        $this->addSql('ALTER TABLE media DROP tags');
    }

    public function down(Schema $schema): void
    {
        $this->addSql("ALTER TABLE media ADD tags JSON DEFAULT '[]' NOT NULL");
        $this->addSql('ALTER TABLE media ALTER tags DROP DEFAULT');

        $this->addSql(<<<'SQL'
            UPDATE media m
            SET tags = COALESCE((
                SELECT json_agg(t.name ORDER BY t.name)
                FROM media_tag mt
                JOIN tag t ON t.id = mt.tag_id
                WHERE mt.media_id = m.id
            ), '[]'::json)
            SQL);

        $this->addSql('DROP TABLE media_tag');
        $this->addSql('DROP TABLE tag');
    }
}
