<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260823093542 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE feed_skip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, skipped_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_78E1BE2AA76ED395 ON feed_skip (user_id)');
        $this->addSql('CREATE INDEX IDX_78E1BE2AEA9FDD75 ON feed_skip (media_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_skip_user_media ON feed_skip (user_id, media_id)');
        $this->addSql('ALTER TABLE feed_skip ADD CONSTRAINT FK_78E1BE2AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feed_skip ADD CONSTRAINT FK_78E1BE2AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE feed_skip DROP CONSTRAINT FK_78E1BE2AA76ED395');
        $this->addSql('ALTER TABLE feed_skip DROP CONSTRAINT FK_78E1BE2AEA9FDD75');
        $this->addSql('DROP TABLE feed_skip');
    }
}
