<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260822102852 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, file_path VARCHAR(255) DEFAULT NULL, original_name VARCHAR(255) DEFAULT NULL, text_content TEXT DEFAULT NULL, url VARCHAR(2048) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pack_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10C1919B217 ON media (pack_id)');
        $this->addSql('CREATE TABLE media_access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BA10B18AA76ED395 ON media_access (user_id)');
        $this->addSql('CREATE INDEX IDX_BA10B18AEA9FDD75 ON media_access (media_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_media ON media_access (user_id, media_id)');
        $this->addSql('CREATE TABLE pack (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, unlock_delay_hours INT NOT NULL, position INT NOT NULL, published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE pack_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_opened_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, pack_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C8EB657A76ED395 ON pack_progress (user_id)');
        $this->addSql('CREATE INDEX IDX_C8EB6571919B217 ON pack_progress (pack_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_pack ON pack_progress (user_id, pack_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, invitation_token VARCHAR(64) DEFAULT NULL, invitation_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64933FC351A ON "user" (invitation_token)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C1919B217 FOREIGN KEY (pack_id) REFERENCES pack (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_access ADD CONSTRAINT FK_BA10B18AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE media_access ADD CONSTRAINT FK_BA10B18AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pack_progress ADD CONSTRAINT FK_C8EB657A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pack_progress ADD CONSTRAINT FK_C8EB6571919B217 FOREIGN KEY (pack_id) REFERENCES pack (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C1919B217');
        $this->addSql('ALTER TABLE media_access DROP CONSTRAINT FK_BA10B18AA76ED395');
        $this->addSql('ALTER TABLE media_access DROP CONSTRAINT FK_BA10B18AEA9FDD75');
        $this->addSql('ALTER TABLE pack_progress DROP CONSTRAINT FK_C8EB657A76ED395');
        $this->addSql('ALTER TABLE pack_progress DROP CONSTRAINT FK_C8EB6571919B217');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE media_access');
        $this->addSql('DROP TABLE pack');
        $this->addSql('DROP TABLE pack_progress');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
