<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Les packs disparaissent : le fil est une seule suite de notifications,
 * chacune portant l'application qu'elle imite et son propre délai d'arrivée.
 */
final class Version20260822223320 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remplace les packs par un fil unique de notifications';
    }

    public function up(Schema $schema): void
    {
        // Les médias de tous les packs deviennent un seul fil : on les renumérote
        // dans l'ordre des packs puis de leur position, avant de perdre pack_id.
        $this->addSql('UPDATE media m SET position = s.rn - 1 FROM (SELECT id, ROW_NUMBER() OVER (ORDER BY pack_id, position, id) AS rn FROM media) s WHERE m.id = s.id');

        // Les DEFAULT sont indispensables : la table peut déjà contenir des
        // médias, et un ALTER ... NOT NULL sans valeur échouerait.
        $this->addSql("ALTER TABLE media ADD app_kind VARCHAR(255) DEFAULT 'uber_eats' NOT NULL");
        $this->addSql("ALTER TABLE media ADD app_data JSON DEFAULT '{}' NOT NULL");
        $this->addSql('ALTER TABLE media ADD published BOOLEAN DEFAULT TRUE NOT NULL');
        $this->addSql('ALTER TABLE media ADD delay_minutes INT DEFAULT 1440 NOT NULL');

        $this->addSql('ALTER TABLE media DROP CONSTRAINT fk_6a2ca10c1919b217');
        $this->addSql('DROP INDEX idx_6a2ca10c1919b217');
        $this->addSql('ALTER TABLE media DROP pack_id');

        $this->addSql('ALTER TABLE pack_progress DROP CONSTRAINT fk_c8eb657a76ed395');
        $this->addSql('ALTER TABLE pack_progress DROP CONSTRAINT fk_c8eb6571919b217');
        $this->addSql('DROP TABLE pack_progress');
        $this->addSql('DROP TABLE pack');

        // Les valeurs par défaut vivent dans l'entité ; la base n'en a plus besoin.
        $this->addSql('ALTER TABLE media ALTER app_kind DROP DEFAULT');
        $this->addSql('ALTER TABLE media ALTER app_data DROP DEFAULT');
        $this->addSql('ALTER TABLE media ALTER published DROP DEFAULT');
        $this->addSql('ALTER TABLE media ALTER delay_minutes DROP DEFAULT');
        $this->addSql('ALTER TABLE media ALTER aura_points DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // Les packs ne peuvent pas être reconstitués : on recrée la structure
        // et on rattache tous les médias à un pack unique.
        $this->addSql('CREATE TABLE pack (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, unlock_delay_minutes INT NOT NULL, "position" INT NOT NULL, published BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql("INSERT INTO pack (name, unlock_delay_minutes, \"position\", published, created_at) VALUES ('Fil', 1440, 0, TRUE, NOW())");

        $this->addSql('CREATE TABLE pack_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_opened_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, pack_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_pack ON pack_progress (user_id, pack_id)');
        $this->addSql('CREATE INDEX idx_c8eb657a76ed395 ON pack_progress (user_id)');
        $this->addSql('CREATE INDEX idx_c8eb6571919b217 ON pack_progress (pack_id)');
        $this->addSql('ALTER TABLE pack_progress ADD CONSTRAINT fk_c8eb657a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pack_progress ADD CONSTRAINT fk_c8eb6571919b217 FOREIGN KEY (pack_id) REFERENCES pack (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE media ADD pack_id INT');
        $this->addSql('UPDATE media SET pack_id = (SELECT MIN(id) FROM pack)');
        $this->addSql('ALTER TABLE media ALTER pack_id SET NOT NULL');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT fk_6a2ca10c1919b217 FOREIGN KEY (pack_id) REFERENCES pack (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_6a2ca10c1919b217 ON media (pack_id)');

        $this->addSql('ALTER TABLE media DROP app_kind');
        $this->addSql('ALTER TABLE media DROP app_data');
        $this->addSql('ALTER TABLE media DROP published');
        $this->addSql('ALTER TABLE media DROP delay_minutes');
        $this->addSql('ALTER TABLE media ALTER aura_points SET DEFAULT 100');
    }
}
